print("Exámen Médico")
esc = input ("Por favor, ingrese el nombre de su escuela: ")
dom = input ("Domicilio: ")
tel = input ("Número telefónico: ")
nom = input ("Nombre del alumno:")
fechaN = input ("Fecha de nacimiento: ")
curp = input ("CURP: ")
nom2 = input ("nombre del padre o tutor: ")
print("Exámen Físico")
print("Estado nutricional")
print("Por favor, inserte el tipo de estado nutricional que describa mejor su estado actual.")
estado = input ("Normal, malnutricion leve, malnutricion moderada, malnutricion severa, sobrepeso, obesidad: ")
print("Digestivo")
print("¿Cuál es su estado digestivo?")
diges = input ("Normal, Diarrea, Parasitosis, otro(en este caso, inserte cual): ")
print ("Sistema para el examen fisico")
peso = int(input ("Para iniciar introduce tu peso:"))
print("¿Cual es tu agudeza visual?")
av = input("normal; disminuida; usa lentes: ")
print("Resultados: ")
print("Escuela:",esc)
print("Nombre del alumno:",nom)
print("Domicilio: ",dom)
print("Numero telefonico: ",tel)
print("Fecha de nacimiento: ",fechaN)
print("CURP: ",curp)
print("Nombre del tutor: ",nom2)
print("Estado fisico: ",estado)
print("Estado digestivo: ",diges)
print("Peso: ",peso)
if peso > 30: 
    print ("saludable")
elif peso >70:
    print ("sobrepeso")
if peso >90:
    print ("exceso de peso")
print("agudeza visual: ",av)

